name: "🐞 Bug Report"
description: Report a problem or unexpected behavior in Homeschool Planner
title: "[BUG] "
labels: ["bug"]
body:
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: "Immediate tasks will be handled before all others. Trivial tasks may be left for later."
      options:
        - Immediate
        - Major
        - Moderate
        - Minor
        - Trivial
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description of the Bug
      description: "Provide a clear and concise description of the bug."
      placeholder: "Example: When clicking Save, the page refreshes instead of saving."
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: "List the steps to duplicate this bug."
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: "What actually happened?"
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: "Provide OS, browser, version, or other relevant details."
      placeholder: "Windows 11, Chrome 128, v1.2.3"
